export const countries: any = {
  BF: {
    name: "Burkina Faso",
    emoji: "🇧🇫",
    image: "https://flagcdn.com/bf.svg",
  },
  HK: { name: "Hong Kong", emoji: "🇭🇰", image: "https://flagcdn.com/hk.svg" },
  AE: {
    name: "United Arab Emirates",
    emoji: "🇦🇪",
    image: "https://flagcdn.com/ae.svg",
  },
  AG: {
    name: "Antigua and Barbuda",
    emoji: "🇦🇬",
    image: "https://flagcdn.com/ag.svg",
  },
  KM: { name: "Comoros", emoji: "🇰🇲", image: "https://flagcdn.com/km.svg" },
  PN: {
    name: "Pitcairn Islands",
    emoji: "🇵🇳",
    image: "https://flagcdn.com/pn.svg",
  },
  BG: { name: "Bulgaria", emoji: "🇧🇬", image: "https://flagcdn.com/bg.svg" },
  DJ: { name: "Djibouti", emoji: "🇩🇯", image: "https://flagcdn.com/dj.svg" },
  LA: { name: "Laos", emoji: "🇱🇦", image: "https://flagcdn.com/la.svg" },
  LB: { name: "Lebanon", emoji: "🇱🇧", image: "https://flagcdn.com/lb.svg" },
  PA: { name: "Panama", emoji: "🇵🇦", image: "https://flagcdn.com/pa.svg" },
  EC: { name: "Ecuador", emoji: "🇪🇨", image: "https://flagcdn.com/ec.svg" },
  BB: { name: "Barbados", emoji: "🇧🇧", image: "https://flagcdn.com/bb.svg" },
  IM: { name: "Isle of Man", emoji: "🇮🇲", image: "https://flagcdn.com/im.svg" },
  BT: { name: "Bhutan", emoji: "🇧🇹", image: "https://flagcdn.com/bt.svg" },
  BI: { name: "Burundi", emoji: "🇧🇮", image: "https://flagcdn.com/bi.svg" },
  CN: { name: "China", emoji: "🇨🇳", image: "https://flagcdn.com/cn.svg" },
  NF: {
    name: "Norfolk Island",
    emoji: "🇳🇫",
    image: "https://flagcdn.com/nf.svg",
  },
  LY: { name: "Libya", emoji: "🇱🇾", image: "https://flagcdn.com/ly.svg" },
  BA: {
    name: "Bosnia and Herzegovina",
    emoji: "🇧🇦",
    image: "https://flagcdn.com/ba.svg",
  },
  TV: { name: "Tuvalu", emoji: "🇹🇻", image: "https://flagcdn.com/tv.svg" },
  AO: { name: "Angola", emoji: "🇦🇴", image: "https://flagcdn.com/ao.svg" },
  MG: { name: "Madagascar", emoji: "🇲🇬", image: "https://flagcdn.com/mg.svg" },
  MR: { name: "Mauritania", emoji: "🇲🇷", image: "https://flagcdn.com/mr.svg" },
  AI: { name: "Anguilla", emoji: "🇦🇮", image: "https://flagcdn.com/ai.svg" },
  JE: { name: "Jersey", emoji: "🇯🇪", image: "https://flagcdn.com/je.svg" },
  CV: { name: "Cape Verde", emoji: "🇨🇻", image: "https://flagcdn.com/cv.svg" },
  VI: {
    name: "United States Virgin Islands",
    emoji: "🇻🇮",
    image: "https://flagcdn.com/vi.svg",
  },
  MP: {
    name: "Northern Mariana Islands",
    emoji: "🇲🇵",
    image: "https://flagcdn.com/mp.svg",
  },
  NU: { name: "Niue", emoji: "🇳🇺", image: "https://flagcdn.com/nu.svg" },
  UM: {
    name: "United States Minor Outlying Islands",
    emoji: "🇺🇲",
    image: "https://flagcdn.com/um.svg",
  },
  MX: { name: "Mexico", emoji: "🇲🇽", image: "https://flagcdn.com/mx.svg" },
  LK: { name: "Sri Lanka", emoji: "🇱🇰", image: "https://flagcdn.com/lk.svg" },
  VE: { name: "Venezuela", emoji: "🇻🇪", image: "https://flagcdn.com/ve.svg" },
  FK: {
    name: "Falkland Islands",
    emoji: "🇫🇰",
    image: "https://flagcdn.com/fk.svg",
  },
  MW: { name: "Malawi", emoji: "🇲🇼", image: "https://flagcdn.com/mw.svg" },
  SM: { name: "San Marino", emoji: "🇸🇲", image: "https://flagcdn.com/sm.svg" },
  TC: {
    name: "Turks and Caicos Islands",
    emoji: "🇹🇨",
    image: "https://flagcdn.com/tc.svg",
  },
  PM: {
    name: "Saint Pierre and Miquelon",
    emoji: "🇵🇲",
    image: "https://flagcdn.com/pm.svg",
  },
  SR: { name: "Suriname", emoji: "🇸🇷", image: "https://flagcdn.com/sr.svg" },
  GN: { name: "Guinea", emoji: "🇬🇳", image: "https://flagcdn.com/gn.svg" },
  ZW: { name: "Zimbabwe", emoji: "🇿🇼", image: "https://flagcdn.com/zw.svg" },
  RW: { name: "Rwanda", emoji: "🇷🇼", image: "https://flagcdn.com/rw.svg" },
  KG: { name: "Kyrgyzstan", emoji: "🇰🇬", image: "https://flagcdn.com/kg.svg" },
  RU: { name: "Russia", emoji: "🇷🇺", image: "https://flagcdn.com/ru.svg" },
  UZ: { name: "Uzbekistan", emoji: "🇺🇿", image: "https://flagcdn.com/uz.svg" },
  BE: { name: "Belgium", emoji: "🇧🇪", image: "https://flagcdn.com/be.svg" },
  AX: {
    name: "Åland Islands",
    emoji: "🇦🇽",
    image: "https://flagcdn.com/ax.svg",
  },
  EH: {
    name: "Western Sahara",
    emoji: "🇪🇭",
    image: "https://flagcdn.com/eh.svg",
  },
  YT: { name: "Mayotte", emoji: "🇾🇹", image: "https://flagcdn.com/yt.svg" },
  MA: { name: "Morocco", emoji: "🇲🇦", image: "https://flagcdn.com/ma.svg" },
  MQ: { name: "Martinique", emoji: "🇲🇶", image: "https://flagcdn.com/mq.svg" },
  FR: { name: "France", emoji: "🇫🇷", image: "https://flagcdn.com/fr.svg" },
  TZ: { name: "Tanzania", emoji: "🇹🇿", image: "https://flagcdn.com/tz.svg" },
  KY: {
    name: "Cayman Islands",
    emoji: "🇰🇾",
    image: "https://flagcdn.com/ky.svg",
  },
  IR: { name: "Iran", emoji: "🇮🇷", image: "https://flagcdn.com/ir.svg" },
  IL: { name: "Israel", emoji: "🇮🇱", image: "https://flagcdn.com/il.svg" },
  CM: { name: "Cameroon", emoji: "🇨🇲", image: "https://flagcdn.com/cm.svg" },
  SG: { name: "Singapore", emoji: "🇸🇬", image: "https://flagcdn.com/sg.svg" },
  HR: { name: "Croatia", emoji: "🇭🇷", image: "https://flagcdn.com/hr.svg" },
  MM: { name: "Myanmar", emoji: "🇲🇲", image: "https://flagcdn.com/mm.svg" },
  GD: { name: "Grenada", emoji: "🇬🇩", image: "https://flagcdn.com/gd.svg" },
  CA: { name: "Canada", emoji: "🇨🇦", image: "https://flagcdn.com/ca.svg" },
  AR: { name: "Argentina", emoji: "🇦🇷", image: "https://flagcdn.com/ar.svg" },
  RE: { name: "Réunion", emoji: "🇷🇪", image: "https://flagcdn.com/re.svg" },
  MY: { name: "Malaysia", emoji: "🇲🇾", image: "https://flagcdn.com/my.svg" },
  SZ: { name: "Eswatini", emoji: "🇸🇿", image: "https://flagcdn.com/sz.svg" },
  FO: {
    name: "Faroe Islands",
    emoji: "🇫🇴",
    image: "https://flagcdn.com/fo.svg",
  },
  SL: {
    name: "Sierra Leone",
    emoji: "🇸🇱",
    image: "https://flagcdn.com/sl.svg",
  },
  UG: { name: "Uganda", emoji: "🇺🇬", image: "https://flagcdn.com/ug.svg" },
  AS: {
    name: "American Samoa",
    emoji: "🇦🇸",
    image: "https://flagcdn.com/as.svg",
  },
  CI: { name: "Ivory Coast", emoji: "🇨🇮", image: "https://flagcdn.com/ci.svg" },
  GQ: {
    name: "Equatorial Guinea",
    emoji: "🇬🇶",
    image: "https://flagcdn.com/gq.svg",
  },
  PK: { name: "Pakistan", emoji: "🇵🇰", image: "https://flagcdn.com/pk.svg" },
  MC: { name: "Monaco", emoji: "🇲🇨", image: "https://flagcdn.com/mc.svg" },
  CK: {
    name: "Cook Islands",
    emoji: "🇨🇰",
    image: "https://flagcdn.com/ck.svg",
  },
  BO: { name: "Bolivia", emoji: "🇧🇴", image: "https://flagcdn.com/bo.svg" },
  CY: { name: "Cyprus", emoji: "🇨🇾", image: "https://flagcdn.com/cy.svg" },
  FJ: { name: "Fiji", emoji: "🇫🇯", image: "https://flagcdn.com/fj.svg" },
  BR: { name: "Brazil", emoji: "🇧🇷", image: "https://flagcdn.com/br.svg" },
  UA: { name: "Ukraine", emoji: "🇺🇦", image: "https://flagcdn.com/ua.svg" },
  PW: { name: "Palau", emoji: "🇵🇼", image: "https://flagcdn.com/pw.svg" },
  BH: { name: "Bahrain", emoji: "🇧🇭", image: "https://flagcdn.com/bh.svg" },
  GM: { name: "Gambia", emoji: "🇬🇲", image: "https://flagcdn.com/gm.svg" },
  PL: { name: "Poland", emoji: "🇵🇱", image: "https://flagcdn.com/pl.svg" },
  CU: { name: "Cuba", emoji: "🇨🇺", image: "https://flagcdn.com/cu.svg" },
  JO: { name: "Jordan", emoji: "🇯🇴", image: "https://flagcdn.com/jo.svg" },
  SI: { name: "Slovenia", emoji: "🇸🇮", image: "https://flagcdn.com/si.svg" },
  TF: {
    name: "French Southern and Antarctic Lands",
    emoji: "🇹🇫",
    image: "https://flagcdn.com/tf.svg",
  },
  TM: {
    name: "Turkmenistan",
    emoji: "🇹🇲",
    image: "https://flagcdn.com/tm.svg",
  },
  LU: { name: "Luxembourg", emoji: "🇱🇺", image: "https://flagcdn.com/lu.svg" },
  GH: { name: "Ghana", emoji: "🇬🇭", image: "https://flagcdn.com/gh.svg" },
  MD: { name: "Moldova", emoji: "🇲🇩", image: "https://flagcdn.com/md.svg" },
  ER: { name: "Eritrea", emoji: "🇪🇷", image: "https://flagcdn.com/er.svg" },
  ES: { name: "Spain", emoji: "🇪🇸", image: "https://flagcdn.com/es.svg" },
  ET: { name: "Ethiopia", emoji: "🇪🇹", image: "https://flagcdn.com/et.svg" },
  MZ: { name: "Mozambique", emoji: "🇲🇿", image: "https://flagcdn.com/mz.svg" },
  SX: {
    name: "Sint Maarten",
    emoji: "🇸🇽",
    image: "https://flagcdn.com/sx.svg",
  },
  SY: { name: "Syria", emoji: "🇸🇾", image: "https://flagcdn.com/sy.svg" },
  BD: { name: "Bangladesh", emoji: "🇧🇩", image: "https://flagcdn.com/bd.svg" },
  VN: { name: "Vietnam", emoji: "🇻🇳", image: "https://flagcdn.com/vn.svg" },
  NL: { name: "Netherlands", emoji: "🇳🇱", image: "https://flagcdn.com/nl.svg" },
  AD: { name: "Andorra", emoji: "🇦🇩", image: "https://flagcdn.com/ad.svg" },
  TW: { name: "Taiwan", emoji: "🇹🇼", image: "https://flagcdn.com/tw.svg" },
  CX: {
    name: "Christmas Island",
    emoji: "🇨🇽",
    image: "https://flagcdn.com/cx.svg",
  },
  WS: { name: "Samoa", emoji: "🇼🇸", image: "https://flagcdn.com/ws.svg" },
  GW: {
    name: "Guinea-Bissau",
    emoji: "🇬🇼",
    image: "https://flagcdn.com/gw.svg",
  },
  PR: { name: "Puerto Rico", emoji: "🇵🇷", image: "https://flagcdn.com/pr.svg" },
  PG: {
    name: "Papua New Guinea",
    emoji: "🇵🇬",
    image: "https://flagcdn.com/pg.svg",
  },
  GG: { name: "Guernsey", emoji: "🇬🇬", image: "https://flagcdn.com/gg.svg" },
  UY: { name: "Uruguay", emoji: "🇺🇾", image: "https://flagcdn.com/uy.svg" },
  AU: { name: "Australia", emoji: "🇦🇺", image: "https://flagcdn.com/au.svg" },
  KP: { name: "North Korea", emoji: "🇰🇵", image: "https://flagcdn.com/kp.svg" },
  BV: {
    name: "Bouvet Island",
    emoji: "🇧🇻",
    image: "https://flagcdn.com/bv.svg",
  },
  EE: { name: "Estonia", emoji: "🇪🇪", image: "https://flagcdn.com/ee.svg" },
  HT: { name: "Haiti", emoji: "🇭🇹", image: "https://flagcdn.com/ht.svg" },
  DZ: { name: "Algeria", emoji: "🇩🇿", image: "https://flagcdn.com/dz.svg" },
  TG: { name: "Togo", emoji: "🇹🇬", image: "https://flagcdn.com/tg.svg" },
  GF: {
    name: "French Guiana",
    emoji: "🇬🇫",
    image: "https://flagcdn.com/gf.svg",
  },
  DM: { name: "Dominica", emoji: "🇩🇲", image: "https://flagcdn.com/dm.svg" },
  ST: {
    name: "São Tomé and Príncipe",
    emoji: "🇸🇹",
    image: "https://flagcdn.com/st.svg",
  },
  EG: { name: "Egypt", emoji: "🇪🇬", image: "https://flagcdn.com/eg.svg" },
  GT: { name: "Guatemala", emoji: "🇬🇹", image: "https://flagcdn.com/gt.svg" },
  NO: { name: "Norway", emoji: "🇳🇴", image: "https://flagcdn.com/no.svg" },
  GR: { name: "Greece", emoji: "🇬🇷", image: "https://flagcdn.com/gr.svg" },
  BY: { name: "Belarus", emoji: "🇧🇾", image: "https://flagcdn.com/by.svg" },
  DK: { name: "Denmark", emoji: "🇩🇰", image: "https://flagcdn.com/dk.svg" },
  HM: {
    name: "Heard Island and McDonald Islands",
    emoji: "🇭🇲",
    image: "https://flagcdn.com/hm.svg",
  },
  ID: { name: "Indonesia", emoji: "🇮🇩", image: "https://flagcdn.com/id.svg" },
  CL: { name: "Chile", emoji: "🇨🇱", image: "https://flagcdn.com/cl.svg" },
  PS: { name: "Palestine", emoji: "🇵🇸", image: "https://flagcdn.com/ps.svg" },
  GB: {
    name: "United Kingdom",
    emoji: "🇬🇧",
    image: "https://flagcdn.com/gb.svg",
  },
  KN: {
    name: "Saint Kitts and Nevis",
    emoji: "🇰🇳",
    image: "https://flagcdn.com/kn.svg",
  },
  BL: {
    name: "Saint Barthélemy",
    emoji: "🇧🇱",
    image: "https://flagcdn.com/bl.svg",
  },
  NI: { name: "Nicaragua", emoji: "🇳🇮", image: "https://flagcdn.com/ni.svg" },
  TN: { name: "Tunisia", emoji: "🇹🇳", image: "https://flagcdn.com/tn.svg" },
  GU: { name: "Guam", emoji: "🇬🇺", image: "https://flagcdn.com/gu.svg" },
  MO: { name: "Macau", emoji: "🇲🇴", image: "https://flagcdn.com/mo.svg" },
  PF: {
    name: "French Polynesia",
    emoji: "🇵🇫",
    image: "https://flagcdn.com/pf.svg",
  },
  FI: { name: "Finland", emoji: "🇫🇮", image: "https://flagcdn.com/fi.svg" },
  SC: { name: "Seychelles", emoji: "🇸🇨", image: "https://flagcdn.com/sc.svg" },
  GS: {
    name: "South Georgia",
    emoji: "🇬🇸",
    image: "https://flagcdn.com/gs.svg",
  },
  JM: { name: "Jamaica", emoji: "🇯🇲", image: "https://flagcdn.com/jm.svg" },
  SK: { name: "Slovakia", emoji: "🇸🇰", image: "https://flagcdn.com/sk.svg" },
  GY: { name: "Guyana", emoji: "🇬🇾", image: "https://flagcdn.com/gy.svg" },
  KH: { name: "Cambodia", emoji: "🇰🇭", image: "https://flagcdn.com/kh.svg" },
  TH: { name: "Thailand", emoji: "🇹🇭", image: "https://flagcdn.com/th.svg" },
  FM: { name: "Micronesia", emoji: "🇫🇲", image: "https://flagcdn.com/fm.svg" },
  MV: { name: "Maldives", emoji: "🇲🇻", image: "https://flagcdn.com/mv.svg" },
  MU: { name: "Mauritius", emoji: "🇲🇺", image: "https://flagcdn.com/mu.svg" },
  NC: {
    name: "New Caledonia",
    emoji: "🇳🇨",
    image: "https://flagcdn.com/nc.svg",
  },
  PH: { name: "Philippines", emoji: "🇵🇭", image: "https://flagcdn.com/ph.svg" },
  SD: { name: "Sudan", emoji: "🇸🇩", image: "https://flagcdn.com/sd.svg" },
  US: {
    name: "United States",
    emoji: "🇺🇸",
    image: "https://flagcdn.com/us.svg",
  },
  JP: { name: "Japan", emoji: "🇯🇵", image: "https://flagcdn.com/jp.svg" },
  GE: { name: "Georgia", emoji: "🇬🇪", image: "https://flagcdn.com/ge.svg" },
  TJ: { name: "Tajikistan", emoji: "🇹🇯", image: "https://flagcdn.com/tj.svg" },
  AQ: { name: "Antarctica", emoji: "🇦🇶", image: "https://flagcdn.com/aq.svg" },
  CG: {
    name: "Republic of the Congo",
    emoji: "🇨🇬",
    image: "https://flagcdn.com/cg.svg",
  },
  RS: { name: "Serbia", emoji: "🇷🇸", image: "https://flagcdn.com/rs.svg" },
  AM: { name: "Armenia", emoji: "🇦🇲", image: "https://flagcdn.com/am.svg" },
  BW: { name: "Botswana", emoji: "🇧🇼", image: "https://flagcdn.com/bw.svg" },
  AF: {
    name: "Afghanistan",
    emoji: "🇦🇫",
    image:
      "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
  },
  QA: { name: "Qatar", emoji: "🇶🇦", image: "https://flagcdn.com/qa.svg" },
  TT: {
    name: "Trinidad and Tobago",
    emoji: "🇹🇹",
    image: "https://flagcdn.com/tt.svg",
  },
  YE: { name: "Yemen", emoji: "🇾🇪", image: "https://flagcdn.com/ye.svg" },
  BN: { name: "Brunei", emoji: "🇧🇳", image: "https://flagcdn.com/bn.svg" },
  IS: { name: "Iceland", emoji: "🇮🇸", image: "https://flagcdn.com/is.svg" },
  BQ: {
    name: "Caribbean Netherlands",
    emoji: "🇧🇶",
    image: "https://flagcdn.com/bq.svg",
  },
  MH: {
    name: "Marshall Islands",
    emoji: "🇲🇭",
    image: "https://flagcdn.com/mh.svg",
  },
  IQ: { name: "Iraq", emoji: "🇮🇶", image: "https://flagcdn.com/iq.svg" },
  CW: { name: "Curaçao", emoji: "🇨🇼", image: "https://flagcdn.com/cw.svg" },
  XK: { name: "Kosovo", emoji: "🇽🇰", image: "https://flagcdn.com/xk.svg" },
  AL: { name: "Albania", emoji: "🇦🇱", image: "https://flagcdn.com/al.svg" },
  VC: {
    name: "Saint Vincent and the Grenadines",
    emoji: "🇻🇨",
    image: "https://flagcdn.com/vc.svg",
  },
  HN: { name: "Honduras", emoji: "🇭🇳", image: "https://flagcdn.com/hn.svg" },
  TK: { name: "Tokelau", emoji: "🇹🇰", image: "https://flagcdn.com/tk.svg" },
  NA: { name: "Namibia", emoji: "🇳🇦", image: "https://flagcdn.com/na.svg" },
  WF: {
    name: "Wallis and Futuna",
    emoji: "🇼🇫",
    image: "https://flagcdn.com/wf.svg",
  },
  LT: { name: "Lithuania", emoji: "🇱🇹", image: "https://flagcdn.com/lt.svg" },
  NE: { name: "Niger", emoji: "🇳🇪", image: "https://flagcdn.com/ne.svg" },
  BJ: { name: "Benin", emoji: "🇧🇯", image: "https://flagcdn.com/bj.svg" },
  IN: { name: "India", emoji: "🇮🇳", image: "https://flagcdn.com/in.svg" },
  ML: { name: "Mali", emoji: "🇲🇱", image: "https://flagcdn.com/ml.svg" },
  NG: { name: "Nigeria", emoji: "🇳🇬", image: "https://flagcdn.com/ng.svg" },
  AW: { name: "Aruba", emoji: "🇦🇼", image: "https://flagcdn.com/aw.svg" },
  SA: {
    name: "Saudi Arabia",
    emoji: "🇸🇦",
    image: "https://flagcdn.com/sa.svg",
  },
  BM: { name: "Bermuda", emoji: "🇧🇲", image: "https://flagcdn.com/bm.svg" },
  MS: { name: "Montserrat", emoji: "🇲🇸", image: "https://flagcdn.com/ms.svg" },
  KZ: { name: "Kazakhstan", emoji: "🇰🇿", image: "https://flagcdn.com/kz.svg" },
  LS: { name: "Lesotho", emoji: "🇱🇸", image: "https://flagcdn.com/ls.svg" },
  KI: { name: "Kiribati", emoji: "🇰🇮", image: "https://flagcdn.com/ki.svg" },
  DO: {
    name: "Dominican Republic",
    emoji: "🇩🇴",
    image: "https://flagcdn.com/do.svg",
  },
  IE: { name: "Ireland", emoji: "🇮🇪", image: "https://flagcdn.com/ie.svg" },
  AZ: { name: "Azerbaijan", emoji: "🇦🇿", image: "https://flagcdn.com/az.svg" },
  KR: { name: "South Korea", emoji: "🇰🇷", image: "https://flagcdn.com/kr.svg" },
  TO: { name: "Tonga", emoji: "🇹🇴", image: "https://flagcdn.com/to.svg" },
  KW: { name: "Kuwait", emoji: "🇰🇼", image: "https://flagcdn.com/kw.svg" },
  OM: { name: "Oman", emoji: "🇴🇲", image: "https://flagcdn.com/om.svg" },
  TD: { name: "Chad", emoji: "🇹🇩", image: "https://flagcdn.com/td.svg" },
  MN: { name: "Mongolia", emoji: "🇲🇳", image: "https://flagcdn.com/mn.svg" },
  MK: {
    name: "North Macedonia",
    emoji: "🇲🇰",
    image: "https://flagcdn.com/mk.svg",
  },
  CD: { name: "DR Congo", emoji: "🇨🇩", image: "https://flagcdn.com/cd.svg" },
  DE: { name: "Germany", emoji: "🇩🇪", image: "https://flagcdn.com/de.svg" },
  HU: { name: "Hungary", emoji: "🇭🇺", image: "https://flagcdn.com/hu.svg" },
  KE: { name: "Kenya", emoji: "🇰🇪", image: "https://flagcdn.com/ke.svg" },
  ZM: { name: "Zambia", emoji: "🇿🇲", image: "https://flagcdn.com/zm.svg" },
  ZA: {
    name: "South Africa",
    emoji: "🇿🇦",
    image: "https://flagcdn.com/za.svg",
  },
  LV: { name: "Latvia", emoji: "🇱🇻", image: "https://flagcdn.com/lv.svg" },
  TL: { name: "Timor-Leste", emoji: "🇹🇱", image: "https://flagcdn.com/tl.svg" },
  PE: { name: "Peru", emoji: "🇵🇪", image: "https://flagcdn.com/pe.svg" },
  CH: { name: "Switzerland", emoji: "🇨🇭", image: "https://flagcdn.com/ch.svg" },
  BS: { name: "Bahamas", emoji: "🇧🇸", image: "https://flagcdn.com/bs.svg" },
  GA: { name: "Gabon", emoji: "🇬🇦", image: "https://flagcdn.com/ga.svg" },
  LR: { name: "Liberia", emoji: "🇱🇷", image: "https://flagcdn.com/lr.svg" },
  SS: { name: "South Sudan", emoji: "🇸🇸", image: "https://flagcdn.com/ss.svg" },
  GI: { name: "Gibraltar", emoji: "🇬🇮", image: "https://flagcdn.com/gi.svg" },
  LC: { name: "Saint Lucia", emoji: "🇱🇨", image: "https://flagcdn.com/lc.svg" },
  PT: { name: "Portugal", emoji: "🇵🇹", image: "https://flagcdn.com/pt.svg" },
  GL: { name: "Greenland", emoji: "🇬🇱", image: "https://flagcdn.com/gl.svg" },
  GP: { name: "Guadeloupe", emoji: "🇬🇵", image: "https://flagcdn.com/gp.svg" },
  MF: {
    name: "Saint Martin",
    emoji: "🇲🇫",
    image: "https://flagcdn.com/mf.svg",
  },
  CR: { name: "Costa Rica", emoji: "🇨🇷", image: "https://flagcdn.com/cr.svg" },
  CZ: { name: "Czechia", emoji: "🇨🇿", image: "https://flagcdn.com/cz.svg" },
  ME: { name: "Montenegro", emoji: "🇲🇪", image: "https://flagcdn.com/me.svg" },
  CC: {
    name: "Cocos (Keeling) Islands",
    emoji: "🇨🇨",
    image: "https://flagcdn.com/cc.svg",
  },
  SE: { name: "Sweden", emoji: "🇸🇪", image: "https://flagcdn.com/se.svg" },
  IO: {
    name: "British Indian Ocean Territory",
    emoji: "🇮🇴",
    image: "https://flagcdn.com/io.svg",
  },
  SO: { name: "Somalia", emoji: "🇸🇴", image: "https://flagcdn.com/so.svg" },
  MT: { name: "Malta", emoji: "🇲🇹", image: "https://flagcdn.com/mt.svg" },
  SH: {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    emoji: "🇸🇭",
    image: "https://flagcdn.com/sh.svg",
  },
  CO: { name: "Colombia", emoji: "🇨🇴", image: "https://flagcdn.com/co.svg" },
  TR: { name: "Turkey", emoji: "🇹🇷", image: "https://flagcdn.com/tr.svg" },
  BZ: { name: "Belize", emoji: "🇧🇿", image: "https://flagcdn.com/bz.svg" },
  SB: {
    name: "Solomon Islands",
    emoji: "🇸🇧",
    image: "https://flagcdn.com/sb.svg",
  },
  VG: {
    name: "British Virgin Islands",
    emoji: "🇻🇬",
    image: "https://flagcdn.com/vg.svg",
  },
  VA: {
    name: "Vatican City",
    emoji: "🇻🇦",
    image: "https://flagcdn.com/va.svg",
  },
  SN: { name: "Senegal", emoji: "🇸🇳", image: "https://flagcdn.com/sn.svg" },
  CF: {
    name: "Central African Republic",
    emoji: "🇨🇫",
    image: "https://flagcdn.com/cf.svg",
  },
  LI: {
    name: "Liechtenstein",
    emoji: "🇱🇮",
    image: "https://flagcdn.com/li.svg",
  },
  NR: { name: "Nauru", emoji: "🇳🇷", image: "https://flagcdn.com/nr.svg" },
  RO: { name: "Romania", emoji: "🇷🇴", image: "https://flagcdn.com/ro.svg" },
  AT: { name: "Austria", emoji: "🇦🇹", image: "https://flagcdn.com/at.svg" },
  NP: { name: "Nepal", emoji: "🇳🇵", image: "https://flagcdn.com/np.svg" },
  PY: { name: "Paraguay", emoji: "🇵🇾", image: "https://flagcdn.com/py.svg" },
  NZ: { name: "New Zealand", emoji: "🇳🇿", image: "https://flagcdn.com/nz.svg" },
  IT: { name: "Italy", emoji: "🇮🇹", image: "https://flagcdn.com/it.svg" },
  SV: { name: "El Salvador", emoji: "🇸🇻", image: "https://flagcdn.com/sv.svg" },
  SJ: {
    name: "Svalbard and Jan Mayen",
    emoji: "🇸🇯",
    image: "https://flagcdn.com/sj.svg",
  },
  VU: { name: "Vanuatu", emoji: "🇻🇺", image: "https://flagcdn.com/vu.svg" },
}
